permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 曹鹏飞
  email: whiskeyfei@gmail.com
  link: whiskeyfei
  weibo: http://weibo.com/whiskeyfei
  github: https://github.com/whiskeyfei

# 站点信息
title: 曹鹏飞的博客 
description: 曹鹏飞的博客
url: http://whiskeyfei.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://tp4.sinaimg.cn/2395897511/180/5739593886/1
favicon: http://tp4.sinaimg.cn/2395897511/180/5739593886/1

# google analytics 设置
ga:
  id: UA-54767140-1
  url: http://whiskeyfei.github.io/

# disqus 设置
disqus:
  shortname: CPF
